import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import Link from "next/link";
import Input from "../../Input/index"
import DelayInput from "../../DelayInput/index"

const H1 = styled.h1`
  color: red;
`;

const Links = styled.div`
  margin-top: 16px;
  display: grid;
  grid-template-columns: 1fr;
  gap: 8px;

  & a {
    text-decoration: underline;
  }
`

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <H1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </H1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div>
          <span>以下styled-componentの各サンプルコードのページへのリンクになります</span>
          <Links>
            <Link href="/badge">
              Badgeの例
            </Link>
            <Link href="/props-sample">
              propsを使う例
            </Link>
            <Link href="/mixin-sample">
              mixinを使う例
            </Link>
            <Link href="/inheritance-sample">
              継承を使う例
            </Link>
            <Link href="/as-sample">
              スタイルを他のコンポーネントで使用する例
            </Link>
            <Link href="/styled-link-sample">
              Next.jsのコンポーネントにスタイルを適用する例
            </Link>
            <Link href="/theme-sample">
              テーマを使う例
            </Link>
          </Links>
        </div>
        <div>
          <Input label={"テスト"}/>
          <p>↑はテスト用Inputコンポーネント</p>
        </div>
        <div>
          {/* TODO:ここの処理はこれでよい？ */}
          <DelayInput onChange={ (event) => {event.target.value}}/>
          <p>↑はテスト用DelayInputInputコンポーネント</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
